// Canonical URLs, hreflang pairs and Open Graph images for every page.
//
// OG images are composed by Cloudinary at delivery time — text is overlaid on
// an existing asset, so there are no new files to generate, store or keep in
// sync. Changing a title changes the card.

export const SITE = 'https://www.nrg-energia.com';
const CLOUD = 'https://res.cloudinary.com/dmegrbq5k/image/upload';

/** Cloudinary treats , and / as delimiters inside l_text, so they need escaping. */
function ogText(s = '') {
  return encodeURIComponent(
    String(s)
      .replace(/<[^>]+>/g, '')
      .replace(/&mdash;/g, '—').replace(/&rsquo;/g, '’').replace(/&amp;/g, '&')
      .replace(/&egrave;/g, 'è').replace(/&eacute;/g, 'é').replace(/&agrave;/g, 'à')
      .replace(/&ugrave;/g, 'ù').replace(/&ograve;/g, 'ò')
      .replace(/&laquo;/g, '«').replace(/&raquo;/g, '»')
      .replace(/\s+/g, ' ').trim(),
  // encodeURIComponent already yields %2C and %2F; Cloudinary decodes the path
  // once more, so these must be double-encoded or they act as delimiters.
  ).replace(/%2C/g, '%252C').replace(/%2F/g, '%252F');
}

const clamp = (s, n) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);

/**
 * A photo card: the page's own image, darkened, with the title and a subtitle.
 * Used for blog posts and for section pages that have a hero photograph.
 */
export function photoCard(publicId, title, subtitle = '') {
  const layers = [
    'c_fill,g_auto,w_1200,h_630',
    // colorize rather than a scrim layer: l_one_pixel is not an asset in this
    // account, and darkening the whole frame keeps white text readable anywhere
    'e_colorize:48,co_rgb:0a1912',
    `l_text:Arial_60_bold:${ogText(clamp(title, 70))},co_white,w_1020,c_fit/fl_layer_apply,g_south_west,x_60,y_${subtitle ? 158 : 74}`,
  ];
  if (subtitle) {
    layers.push(`l_text:Arial_30:${ogText(clamp(subtitle, 96))},co_rgb:cfe6d7,w_1020,c_fit/fl_layer_apply,g_south_west,x_60,y_64`);
  }
  return `${CLOUD}/${layers.join('/')}/${publicId}`;
}

/**
 * Brand cards are pre-rendered to og/*.jpg by scripts/make-og-cards.mjs, using
 * headless Chrome so they carry the real dot-grid mark and the Syne wordmark.
 * Cloudinary can only set type in fonts it hosts, which meant Arial.
 */
export function brandAsset(name) {
  return `${SITE}/og/${name}.jpg`;
}

/** Cloudinary-composed fallback, kept for reference. Not used by the page map. */
export function brandCard(lang, tagline) {
  const hours = lang === 'it'
    ? 'Lun–Ven 8:30–12:30 · 14:30–18:30 · Imola (BO)'
    : 'Mon–Fri 8:30–12:30 · 14:30–18:30 · Imola, Italy';
  return [
    CLOUD,
    'c_fill,g_auto,w_1200,h_630',
    'e_colorize:88,co_rgb:12301f',
    `l_text:Arial_92_bold:${ogText('NRG ENERGIA')},co_white,w_1040,c_fit/fl_layer_apply,g_center,y_-78`,
    `l_text:Arial_40:${ogText(clamp(tagline, 78))},co_rgb:cfe6d7,w_1040,c_fit/fl_layer_apply,g_center,y_10`,
    `l_text:Arial_28:${ogText(hours)},co_rgb:9dbcab,w_1040,c_fit/fl_layer_apply,g_center,y_96`,
    'v1788802289/watt-a-lot-Ja8t8nJN2I4-unsplash_hvypdi.jpg',
  ].join('/');
}

// ── page map ─────────────────────────────────────────────────────────────────
// Each entry pairs an Italian page with its English twin so hreflang can point
// both ways, and gives the description and OG card for each side.
const TAGLINE = {
  it: 'Energie rinnovabili, coperture e bonifica amianto',
  en: 'Renewable energy, roofing and asbestos removal',
};

// blog.html and services/en/blog.html are intentionally absent: they are
// generated by scripts/render.mjs, which injects their own SEO block.
export const PAGES = [
  {
    it: {
      file: 'index.html', url: '/index',
      title: 'NRG Energia — Energie Rinnovabili e Ambiente',
      description: 'Progettazione e installazione di impianti fotovoltaici, coperture e bonifica amianto in Emilia-Romagna. Gestiamo l’intero processo internamente.',
      og: () => brandAsset('home-it'),
    },
    en: {
      file: 'index.html', url: '/index?lang=en',
      title: 'NRG Energia — Renewable Energy & Environment',
      description: 'Design and installation of solar systems, roofing and asbestos removal in Emilia-Romagna, Italy. The whole process handled in house.',
      og: () => brandAsset('home-en'),
    },
    sharedFile: true,   // one file serves both languages via the JS toggle
  },
  {
    it: { file: 'portfolio.html', url: '/portfolio', title: 'Portfolio — NRG Energia',
      description: 'I nostri progetti realizzati: impianti fotovoltaici, coperture e bonifica amianto in Emilia-Romagna.',
      og: () => photoCard('v1780915275/2_FOTO_Impianti_fotovoltaici_residenziali_integrati_su_pannello_sandwich_finto_coppo_a_Mordano._bem5kz.jpg', 'Portfolio', TAGLINE.it) },
    en: { file: 'services/en/portfolio.html', url: '/services/en/portfolio', title: 'Portfolio — NRG Energia',
      description: 'Our completed projects: solar systems, roofing and asbestos removal across Emilia-Romagna, Italy.',
      og: () => photoCard('v1780915275/2_FOTO_Impianti_fotovoltaici_residenziali_integrati_su_pannello_sandwich_finto_coppo_a_Mordano._bem5kz.jpg', 'Portfolio', TAGLINE.en) },
  },
  {
    it: { file: 'services/energie-rinnovabili.html', url: '/services/energie-rinnovabili', title: 'Energie rinnovabili — NRG Energia',
      description: 'Impianti fotovoltaici e sistemi di accumulo: consulenza, progettazione e installazione con un unico interlocutore.',
      og: () => photoCard('v1780577122/siwawut-phoophinyo-JlhvFEVMwng-unsplash_bf5fjr.jpg', 'Energie rinnovabili', 'Fotovoltaico e sistemi di accumulo') },
    en: { file: 'services/en/renewable-energy.html', url: '/services/en/renewable-energy', title: 'Renewable energy — NRG Energia',
      description: 'Solar systems and battery storage: consultancy, design and installation from a single point of contact.',
      og: () => photoCard('v1780577122/siwawut-phoophinyo-JlhvFEVMwng-unsplash_bf5fjr.jpg', 'Renewable energy', 'Solar systems and battery storage') },
  },
  {
    it: { file: 'services/coperture.html', url: '/services/coperture', title: 'Coperture — NRG Energia',
      description: 'Rifacimento e manutenzione di coperture civili e industriali, con sistemi di sicurezza in quota.',
      og: () => photoCard('v1780486648/IMG_1782_exapgs.jpg', 'Coperture', 'Civili e industriali, in sicurezza') },
    en: { file: 'services/en/roofing.html', url: '/services/en/roofing', title: 'Roofing — NRG Energia',
      description: 'Roof replacement and maintenance for homes and industrial buildings, with fall-protection systems.',
      og: () => photoCard('v1780486648/IMG_1782_exapgs.jpg', 'Roofing', 'Residential and industrial, done safely') },
  },
  {
    it: { file: 'services/bonifica-amianto.html', url: '/services/bonifica-amianto', title: 'Bonifica amianto — NRG Energia',
      description: 'Rimozione e smaltimento certificato dell’amianto, con rifacimento della copertura a norma.',
      og: () => photoCard('v1780584349/iStock-92238282_iz2itk.jpg', 'Bonifica amianto', 'Rimozione e smaltimento certificato') },
    en: { file: 'services/en/asbestos-removal.html', url: '/services/en/asbestos-removal', title: 'Asbestos removal — NRG Energia',
      description: 'Certified asbestos removal and disposal, with compliant replacement of the roof covering.',
      og: () => photoCard('v1780584349/iStock-92238282_iz2itk.jpg', 'Asbestos removal', 'Certified removal and disposal') },
  },
  {
    it: { file: 'services/impianti-elettrici.html', url: '/services/impianti-elettrici', title: 'Impianti elettrici — NRG Energia',
      description: 'Impianti elettrici civili e industriali: progettazione, installazione e messa a norma.',
      og: () => brandAsset('elettrici-it') },
    en: { file: 'services/en/electrical-systems.html', url: '/services/en/electrical-systems', title: 'Electrical systems — NRG Energia',
      description: 'Residential and industrial electrical systems: design, installation and compliance.',
      og: () => brandAsset('elettrici-en') },
  },
];

/** The <meta> and <link> block for one side of a page pair. */
export function metaBlock({ lang, self, alt, title, description, ogImage, type = 'website' }) {
  const locale = lang === 'it' ? 'it_IT' : 'en_GB';
  return [
    `  <link rel="canonical" href="${SITE}${self}"/>`,
    `  <link rel="alternate" hreflang="it" href="${SITE}${alt.it}"/>`,
    `  <link rel="alternate" hreflang="en" href="${SITE}${alt.en}"/>`,
    `  <link rel="alternate" hreflang="x-default" href="${SITE}${alt.it}"/>`,
    `  <meta property="og:type" content="${type}"/>`,
    `  <meta property="og:site_name" content="NRG Energia"/>`,
    `  <meta property="og:locale" content="${locale}"/>`,
    `  <meta property="og:url" content="${SITE}${self}"/>`,
    `  <meta property="og:title" content="${escapeAttr(title)}"/>`,
    `  <meta property="og:description" content="${escapeAttr(description)}"/>`,
    `  <meta property="og:image" content="${ogImage}"/>`,
    `  <meta property="og:image:width" content="1200"/>`,
    `  <meta property="og:image:height" content="630"/>`,
    `  <meta name="twitter:card" content="summary_large_image"/>`,
    `  <meta name="twitter:title" content="${escapeAttr(title)}"/>`,
    `  <meta name="twitter:description" content="${escapeAttr(description)}"/>`,
    `  <meta name="twitter:image" content="${ogImage}"/>`,
  ].join('\n');
}

export function escapeAttr(s = '') {
  return String(s)
    .replace(/&(?![a-zA-Z]+;|#\d+;)/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
